### ISSUE TITLE
Validation error: order_id already exists on another payment

### ISSUE THREAD

**Issue by nitech** [quantity-digital/commerce-quickpay#23]
Getting the error `order_id already exists on another payment` when I try to pay an order. Using sandbox env. on QuickPay

![image](https://github.com/quantity-digital/commerce-quickpay/assets/1279436/88e271e6-3305-4c64-91a6-dea1660c7c7f)

- QuickPay 4.2.0
- Commerce 4.5.2
- Craft 4.8.4

**Comment by bjerringgaard** [comment]
This error occurs if an order already exists in Quickpay with the supplied id, the order_id in quickpay, should correspond to the reference in craftcms. 

Usually happens in one of to cases:
- You have an error in your Craft setup, which is sending the same id everytime (Have seen this preiviously where the id/reference was always set to 7)

- The quickpay account has been used previously, and the id being supplied from the new craft shop, matches with an old order.
