### ISSUE TITLE
Gateway not redirecting

### ISSUE THREAD

**Issue by peterurban** [quantity-digital/commerce-quickpay#4]
I just added the plugin to a client site for testing.

When submitting the payment form, the page will often return/reload the page, with no errors shown in the code or logs. When clicking the submit button multiple times, I can get the gateway to redirect to QuickPay and finish the payment as expected.

The logs show `Undefined property: stdClass::$id'` in cart errors, but I don't know whether this relates to the issue or something else.

Is any special setup needed for this gateway compared to some of the "official" plugins (e.g., Stripe)?

**Craft Version**: 4.3.1
**Commerce Version**: 4.2.2
**Plugin Version**: 4.0.0

**Comment by CMeldgaard** [comment]
Hi,

We are aware of this error issue not being handle properly. This error usually happens if the orderId that is sent to Quickpay isn't unique.

We have on our todo, to make a better error handling of the specific error.

**Comment by CMeldgaard** [comment]
Closed, as version 4.1.0 returns better error messages now
